// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// ignore: uri_does_not_exist
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXpT3Xtf0GikWyJJE5FlHfElE8FDhfvnM',
    appId: '1:838044488794:web:a6d6ad303771736c8c3463',
    messagingSenderId: '838044488794',
    projectId: 'contact-app-3997a',
    authDomain: 'contact-app-3997a.firebaseapp.com',
    storageBucket: 'contact-app-3997a.firebasestorage.app',
    measurementId: 'G-JN1C6HG21Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1SJ62q1bfvErxHxsm7qne6n32GwNm1w8',
    appId: '1:838044488794:android:8fb1e135d5f1b94d8c3463',
    messagingSenderId: '838044488794',
    projectId: 'contact-app-3997a',
    storageBucket: 'contact-app-3997a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx06ODRqNIpT6-E7H8bCj6d55HgMiAArc',
    appId: '1:838044488794:ios:e015007395cad5c48c3463',
    messagingSenderId: '838044488794',
    projectId: 'contact-app-3997a',
    storageBucket: 'contact-app-3997a.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx06ODRqNIpT6-E7H8bCj6d55HgMiAArc',
    appId: '1:838044488794:ios:e015007395cad5c48c3463',
    messagingSenderId: '838044488794',
    projectId: 'contact-app-3997a',
    storageBucket: 'contact-app-3997a.firebasestorage.app',
    iosBundleId: 'com.example.contactApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXpT3Xtf0GikWyJJE5FlHfElE8FDhfvnM',
    appId: '1:838044488794:web:4bc4822601e234eb8c3463',
    messagingSenderId: '838044488794',
    projectId: 'contact-app-3997a',
    authDomain: 'contact-app-3997a.firebaseapp.com',
    storageBucket: 'contact-app-3997a.firebasestorage.app',
    measurementId: 'G-HXVK9GRS98',
  );
}
